import { Apartment } from "@/types/apartment";

export const apartments: Apartment[] = [
  {
    id: '1',
    name: 'Сучасна квартира біля метро',
    description: 'Затишна 1-кімнатна квартира поруч з метро Оболонь.',
    price: 12000,
    location: 'вул. Оболонський проспект, 15',
    geometry: {
      type: 'Point',
      coordinates: [30.4989, 50.4896],
    },
  },
  {
    id: '2',
    name: 'ЖК Комфорт Таун',
    description: '2-кімнатна квартира з ремонтом у сучасному житловому комплексі.',
    price: 18000,
    location: 'вул. Регенераторна, 4',
    geometry: {
      type: 'Point',
      coordinates: [30.6346, 50.4415],
    },
  },
  {
    id: '3',
    name: 'Квартира з видом на Дніпро',
    description: 'Простора 3-кімнатна квартира на Подолі з панорамним видом.',
    price: 25000,
    location: 'вул. Набережно-Хрещатицька, 35',
    geometry: {
      type: 'Point',
      coordinates: [30.5172, 50.4644],
    },
  },
  {
    id: '4',
    name: 'Квартира біля парку Шевченка',
    description: '1-кімнатна квартира в центрі Києва біля парку.',
    price: 15000,
    location: 'вул. Терещенківська, 13',
    geometry: {
      type: 'Point',
      coordinates: [30.5119, 50.4448],
    },
  },
  {
    id: '5',
    name: 'Новобудова на Печерську',
    description: 'Елітна квартира з охороною та підземним паркінгом.',
    price: 32000,
    location: 'вул. Драгомирова, 14',
    geometry: {
      type: 'Point',
      coordinates: [30.5534, 50.4083],
    },
  },
  {
    id: '6',
    name: 'Затишна квартира біля Лук’янівки',
    description: 'Оновлена квартира з меблями та технікою.',
    price: 14000,
    location: 'вул. Дегтярівська, 25',
    geometry: {
      type: 'Point',
      coordinates: [30.4698, 50.4564],
    },
  },
  {
    id: '7',
    name: 'Апартаменти у ЖК Файна Таун',
    description: 'Новий комплекс з інфраструктурою та охороною.',
    price: 20000,
    location: 'вул. Салютна, 2',
    geometry: {
      type: 'Point',
      coordinates: [30.4175, 50.4739],
    },
  },
  {
    id: '8',
    name: 'Квартира біля метро Лівобережна',
    description: 'Світла квартира у спальному районі.',
    price: 11000,
    location: 'вул. Євгена Сверстюка, 6',
    geometry: {
      type: 'Point',
      coordinates: [30.6028, 50.4503],
    },
  },
  {
    id: '9',
    name: 'Квартира на Солом’янці',
    description: 'Бюджетний варіант для студентів та молодих пар.',
    price: 10000,
    location: 'вул. Солом’янська, 20',
    geometry: {
      type: 'Point',
      coordinates: [30.4661, 50.4267],
    },
  },
  {
    id: '10',
    name: 'Панорамна квартира на Троєщині',
    description: 'Вид на Десну, простора кухня-студія.',
    price: 13000,
    location: 'вул. Закревського, 95',
    geometry: {
      type: 'Point',
      coordinates: [30.6275, 50.5123],
    },
  },
  {
    id: '11',
    name: 'Лофт в центрі',
    description: 'Сучасний дизайн у історичному центрі Києва.',
    price: 27000,
    location: 'вул. Велика Васильківська, 45',
    geometry: {
      type: 'Point',
      coordinates: [30.5193, 50.4349],
    },
  },
  {
    id: '12',
    name: 'Квартира біля Арсенальної',
    description: 'Класичний стиль, висока стеля, історичний будинок.',
    price: 22000,
    location: 'вул. Івана Мазепи, 10',
    geometry: {
      type: 'Point',
      coordinates: [30.5451, 50.4361],
    },
  },
  {
    id: '13',
    name: '1-кімнатна біля метро Позняки',
    description: 'Чудовий варіант для молодої пари або студента.',
    price: 10500,
    location: 'вул. Срібнокільська, 3а',
    geometry: {
      type: 'Point',
      coordinates: [30.6295, 50.3952],
    },
  },
  {
    id: '14',
    name: 'ЖК Новопечерські Липки',
    description: 'Елітна новобудова з охороною, паркінгом, басейном.',
    price: 40000,
    location: 'вул. Драгомирова, 16',
    geometry: {
      type: 'Point',
      coordinates: [30.5539, 50.4098],
    },
  },
  {
    id: '15',
    name: 'Бюджетна студія біля метро Лук’янівка',
    description: 'Недорога квартира для довготривалої оренди.',
    price: 9000,
    location: 'вул. Чорновола, 23',
    geometry: {
      type: 'Point',
      coordinates: [30.4826, 50.4552],
    },
  },
  {
    id: '16',
    name: 'Панорамні апартаменти біля Ocean Plaza',
    description: 'Вид на центр, 18 поверх, сучасний ремонт.',
    price: 26000,
    location: 'вул. Антоновича, 172',
    geometry: {
      type: 'Point',
      coordinates: [30.5212, 50.4113],
    },
  },
  {
    id: '17',
    name: '2-кімнатна біля Дарницької площі',
    description: 'Зручна локація, свіжий ремонт, меблі IKEA.',
    price: 14000,
    location: 'вул. Харківське шосе, 19',
    geometry: {
      type: 'Point',
      coordinates: [30.6532, 50.4298],
    },
  },
  {
    id: '18',
    name: 'Квартира біля ботсаду Фоміна',
    description: 'Класика + близькість до університету.',
    price: 17000,
    location: 'вул. Симона Петлюри, 10',
    geometry: {
      type: 'Point',
      coordinates: [30.4954, 50.4442],
    },
  },
  {
    id: '19',
    name: 'Сучасна квартира на Березняках',
    description: 'Поруч школа, парк та Дніпро.',
    price: 12500,
    location: 'вул. Березняківська, 12',
    geometry: {
      type: 'Point',
      coordinates: [30.6177, 50.4261],
    },
  },
  {
    id: '20',
    name: 'Студія біля Контрактової площі',
    description: 'У центрі Подолу, все поруч.',
    price: 16000,
    location: 'вул. Хорива, 2',
    geometry: {
      type: 'Point',
      coordinates: [30.5149, 50.4653],
    },
  },
  {
    id: '21',
    name: 'ЖК Славутич',
    description: 'Новобудова на березі Дніпра, комфорт клас.',
    price: 22000,
    location: 'вул. Зарічна, 10',
    geometry: {
      type: 'Point',
      coordinates: [30.6333, 50.3819],
    },
  },
  {
    id: '22',
    name: '3-кімнатна на Виноградарі',
    description: 'Простора квартира з видом на ліс.',
    price: 14500,
    location: 'вул. Межова, 15',
    geometry: {
      type: 'Point',
      coordinates: [30.3831, 50.4921],
    },
  },
  {
    id: '23',
    name: 'Бізнес-клас біля Золотих Воріт',
    description: 'Престижне розташування, дизайнерський інтер’єр.',
    price: 35000,
    location: 'вул. Ярославів Вал, 10',
    geometry: {
      type: 'Point',
      coordinates: [30.5145, 50.4488],
    },
  },
  {
    id: '24',
    name: '1-кімнатна на Деміївці',
    description: 'Зручна розв’язка, свіжий ремонт.',
    price: 11500,
    location: 'вул. Васильківська, 17',
    geometry: {
      type: 'Point',
      coordinates: [30.5072, 50.4028],
    },
  },
  {
    id: '25',
    name: 'Квартира біля метро Академмістечко',
    description: 'Поруч ліс, ринок, спокійний район.',
    price: 10000,
    location: 'вул. Академіка Булаховського, 3',
    geometry: {
      type: 'Point',
      coordinates: [30.3556, 50.4663],
    },
  },
  {
    id: '26',
    name: 'Мансарда в центрі',
    description: 'Атмосферна квартира з дерев’яними балками.',
    price: 18000,
    location: 'вул. Липинського, 4',
    geometry: {
      type: 'Point',
      coordinates: [30.5056, 50.4521],
    },
  },
  {
    id: '27',
    name: '2-кімнатна на Троєщині',
    description: 'Недорогий варіант у панельному будинку.',
    price: 9500,
    location: 'вул. Милославська, 32',
    geometry: {
      type: 'Point',
      coordinates: [30.6478, 50.5132],
    },
  },
  {
    id: '28',
    name: 'Елітна квартира на Печерську',
    description: 'Величезна площа, панорамні вікна, тиша.',
    price: 45000,
    location: 'вул. Мічуріна, 28',
    geometry: {
      type: 'Point',
      coordinates: [30.5477, 50.4174],
    },
  },
  {
    id: '29',
    name: 'Старий фонд біля цирку',
    description: 'Аутентична квартира з ремонтом в історичному будинку.',
    price: 16000,
    location: 'вул. Бульварно-Кудрявська, 18',
    geometry: {
      type: 'Point',
      coordinates: [30.4905, 50.4478],
    },
  },
  {
    id: '30',
    name: 'Тиха квартира на Святошино',
    description: 'Місце для життя без зайвого шуму.',
    price: 10500,
    location: 'вул. Львівська, 12',
    geometry: {
      type: 'Point',
      coordinates: [30.3743, 50.4549],
    },
  }
]